### ISSUE TITLE
Erweiterung für den Framing Assistant

### ISSUE THREAD

**Issue by JohannesWorks** [christian-photo/ninaAPI#10]
Hallo,
ich traue mich schon fast nicht mehr zu fragen. 
Wäre es möglich, hier auch eine Schnittstelle zur Verfügung zu stellen?

Mir geht es vor allem um die Koordinateneingabe, die "Schwenken und Zentrierenfunktion" und die Kameradrehung.

**Comment by christian-photo** [comment]
Hallo,
kein Problem, immer her mit den Vorschlägen! Die Koordinateneingabe sollte kein Problem sein. Allerdings wird nur eine Schwenken Funktion bereitgestellt, zentriert wird dort aber nicht. Die Kameradrehung ist auch umsetzbar.

**Comment by christian-photo** [comment]
wenn ich schonmal dabei bin: gibt es noch andere Sachen hier die eventuell nützlich wären?

**Comment by JohannesWorks** [comment]
Hmm, du meinst allgemein oder der Framing-Assistent?
Kann ich die irgendwie anders erreichen? Discord, EMail ...?
Würde es einfacher machen, das Ganze zu besprechen.

Mein Ziel ist es, eine möglichst simple Oberfläche zu schaffen. Die im besten Fall per Smartphone bedienbar ist und die wichtigsten Funktionen beinhaltet, um eine Aufnahme mit NINA zu starten.
1. Teleskop aufbauen und alles verbinden.
2. Teleskop ausrichten
3. Teleskop fokussieren
4. Ziel anfahren und Kameradrehung prüfen
5. Guider starten
6. Aufnahme (Sequener) starten

Cool wäre es noch, wenn man den Legacy Sequencer befüllen könnte.

**Comment by christian-photo** [comment]
Auf discord bin ich unter chris_0423 vertreten, dann können wir da uns weiter austauschen. Dann könnte ich auch immer mal wieder Testversionen dir schicken zum ausprobieren.

Deine Auflistung wird zwar noch ein bisschen Zeit brauchen, aber die eine oder andere Sache geht ja schon mit der jetzigen api.

**Comment by JohannesWorks** [comment]
Alles klar.
Unterhalten wir uns auf Discord weiter.
Ich habe dir gerade eine Anfrage geschickt. Ich heiße dort johannesm_15837
