### ISSUE TITLE
404 on /v2/api/equipment/rotator/* routes

### ISSUE THREAD

**Issue by USA-RedDragon** [christian-photo/ninaAPI#12]
Hello, thanks for the project! I went through the equipment `/info` endpoints and found that routes under rotator [`/info`, `/connect`, `/disconnect`] all fail with a 404 error. It seems to only affect the rotator.

I have v2.0.0.2 installed from the Nina plugins tab (though `/v2/api/version` reports 1.0.0.0). I can test against the git head if you'd like me to

**Comment by christian-photo** [comment]
That's strange... can you show me your specific requests? You don't need to test it against the gut head, I can do that myself and see. I am currently working a lot on it

**Comment by USA-RedDragon** [comment]
![Screenshot_20241218_030535_Termux](https://github.com/user-attachments/assets/4db18bce-c56c-4cd2-8023-f0703646bf29)
Sure, here's the issue using curl

**Comment by christian-photo** [comment]
Ohhh I realized what I have done wrong... I will have a new update coming up around christmas, until then you can use this version I quickly compiled: [new dll](https://drive.google.com/file/d/1SsdCfJ0DO6Q7iVd5bst1iSaXhO0z9IIn/view?usp=sharing). Copy that file to `%localappdata%\NINA\Plugins\Advanced API` and replace the existing one

**Comment by christian-photo** [comment]
Fixed in v2.1.0.0
