### ISSUE TITLE
Websocket: Der Verbindungsstatus wird nicht übermittelt  

### ISSUE THREAD

**Issue by MaierJoh** [christian-photo/ninaAPI#9]
Hallo,
laut deiner Doku sollte eine Nachricht so aussehen:
`{
   "Response": {
      "Event": "CAMERA-CONNECTION",
      "Connected": true,
      "Time": "2024-08-07T15:05:03.2217104+02:00"
   },
   "Error": "",
   "Success": true,
   "Type": "API"
}`

Bei mir wird aber der "Connected" Status nicht übermittlet.

`< {"Response":{
    "Event":"CAMERA-CONNECTION",
    "Time":"2024-11-24T19:46:06.0353881+01:00"
    },
      "Error":"",
      "StatusCode":200,
      "Success":true,
      "Type":"API"
}`

Habe ich was übersehen?

Gruß
Johannes

**Comment by christian-photo** [comment]
Hi,
Die Websocket Dokumentation für die v2 Version befindet sich [hier](https://github.com/christian-photo/ninaAPI/wiki/V2#websocket). Ich glaube das sollte ich nochmal deutlicher machen in dem Wiki, das ist wirklich nicht ganz offensichtlich.
Der Status wird nicht mehr übermittelt, da dies nur sehr unzuverlässig funktioniert hat. Stattdessen kann der Client bei jedem Connection Event einfach den bool "umdrehen". Am Anfang ist ja alles disconnected bzw. das kann ja über die Info von dem jeweiligen Device erfragt werden.

**Comment by MaierJoh** [comment]
Ich verstehe.
Dann werde ich den Status einfach bei einem Event abfragen.
Danke.
